package MyColor.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AllColorsPlaceHolder = 0;
  public static final int Color = 1;
  public static final int ColorReference = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x97c1388be8914959L, 0x85e03de45135ef54L);
    builder.put(0x6f96d929fafe5854L, AllColorsPlaceHolder);
    builder.put(0x59b6c2a98c4e9873L, Color);
    builder.put(0x59b6c2a98c4e9876L, ColorReference);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
