package MyShapes.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import MyShapes.generator.helpers.DrawHelpers;
import BaseLanguage.Utils.Code.ColorHelpers;
import java.awt.Dimension;

public class MyCanvas extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics g) {
      super.paintComponent(g);
      DrawHelpers.DrawSquare(g, 100, 100, 100, ColorHelpers.GetColor("yellow"));
      DrawHelpers.DrawCircle(g, 100, 100, 100, ColorHelpers.GetColor("GREEN"));
      DrawHelpers.DrawSquare(g, 1, 2, 20, ColorHelpers.GetColor("RED"));
      DrawHelpers.DrawCircle(g, 200, 200, 100, ColorHelpers.GetColor("blue"));
    }
  };

  private void initialize() {
    this.setTitle("MyCanvas");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }

  public static void main(String[] args) {
    MyCanvas canvas = new MyCanvas();
    canvas.initialize();
  }
}
