package MyShapes.Enhanced.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Indent;
import jetbrains.mps.nodeEditor.cells.EditorCell_Component;
import javax.swing.JComponent;
import MyShapes.Enhanced.behavior.Helpers;

/*package*/ class Circle_ShapePreview_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public Circle_ShapePreview_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createCollection_0();
  }

  private EditorCell createCollection_0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Indent());
    editorCell.setCellId("Collection_347ksb_a");
    editorCell.setBig(true);
    setCellContext(editorCell);
    editorCell.addEditorCell(createNextEditor_0());
    editorCell.addEditorCell(createJComponent_0());
    return editorCell;
  }
  private EditorCell createNextEditor_0() {
    try {
      getCellFactory().pushCellContext();
      getCellFactory().removeCellContextHints(new String[]{"MyShapes.Enhanced.editor.Shapes.ShapePreview"});
      {
        EditorCell editorCell = getCellFactory().createEditorCell(myNode, false, Circle_ShapePreview_Editor.class);
        return editorCell;
      }
    } finally {
      getCellFactory().popCellContext();
    }
  }
  private EditorCell createJComponent_0() {
    EditorCell editorCell = EditorCell_Component.createComponentCell(getEditorContext(), myNode, _QueryFunction_JComponent_347ksb_a1a(), "JComponent_347ksb_b0");
    editorCell.setCellId("JComponent_347ksb_b0_0");
    return editorCell;
  }
  private JComponent _QueryFunction_JComponent_347ksb_a1a() {
    return Helpers.CreateCircleShapePreviewComponent(myNode);
  }
}
