package BaseLanguage.Utils.Code;

/*Generated by MPS */

import java.awt.Color;

public final class ColorHelpers {
  public static Color GetColor(String colorName) {
    Color color = null;
    try {
      color = (Color) Color.class.getField(colorName).get(null);
    } catch (Exception e) {
    }
    return color;
  }
}
