package MyShapes.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "MyShapes";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (concept.getName()) {
        case "Circle":
          return Collections.<NodeFactory>singletonList(new MyShapesFactory.NodeFactory_7126740561890823407());
        case "Shape":
          return Collections.<NodeFactory>singletonList(new MyShapesFactory.NodeFactory_7126740561890812868());
        case "Square":
          return Collections.<NodeFactory>singletonList(new MyShapesFactory.NodeFactory_7126740561890766482());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

}
