package MyShapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int EmptyShape = 2;
  public static final int Shape = 3;
  public static final int Square = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf27753254788418aL, 0xb75972b67f771c05L);
    builder.put(0x59b6c2a98c4cf37dL, Canvas);
    builder.put(0x59b6c2a98c4d040aL, Circle);
    builder.put(0x461f6ef2073128f1L, EmptyShape);
    builder.put(0x59b6c2a98c4cf955L, Shape);
    builder.put(0x59b6c2a98c4d040bL, Square);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
